### ISSUE TITLE
Resource pack not uploading

### ISSUE THREAD

**Issue by Asaredapvp2** [NichtStudioCode/MiniatureBlocks#1]
I downloaded plugin on my server. After i build something on building world when i try to save it into /miniatures there is text on chat : An error occured while uploading the resource pack . I dont know what to do. Please help

**Comment by NichtStudioCode** [comment]
Could you provide the server log?

**Comment by OMGItsMatty** [comment]
Hey im getting the same error.

Console error:

11.07 16:08:59 [Server] INFO HROXz issued server command: /createminiature TEst
11.07 16:09:01 [Server] WARN java.io.IOException: Server responded with non-OK status: 500
11.07 16:09:01 [Server] WARN at de.studiocode.miniatureblocks.utils.HttpMultipartRequest.complete(HttpMultipartRequest.kt:63)
11.07 16:09:01 [Server] WARN at de.studiocode.miniatureblocks.utils.FileIOUploadUtils.uploadFile(FileIOUploadUtils.kt:13)
11.07 16:09:01 [Server] WARN at de.studiocode.miniatureblocks.resourcepack.ResourcePack.upload(ResourcePack.kt:49)
11.07 16:09:01 [Server] WARN at de.studiocode.miniatureblocks.resourcepack.forced.ForcedResourcePack$force$1.run(ForcedResourcePack.kt:18)
11.07 16:09:01 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by Asaredapvp2** [comment]
This is the console after i used /createminiature (name)          Its the same error that have OMGItsMatty
[WARNING] java.io.IOException: Server responded with non-OK status: 500
[WARNING] at de.studiocode.miniatureblocks.utils.HttpMultipartRequest.complete(HttpMultipartRequest.kt:63)
[WARNING] at de.studiocode.miniatureblocks.utils.FileIOUploadUtils.uploadFile(FileIOUploadUtils.kt:13)
[WARNING] at de.studiocode.miniatureblocks.resourcepack.ResourcePack.upload(ResourcePack.kt:49)
[WARNING] at de.studiocode.miniatureblocks.resourcepack.forced.ForcedResourcePack$force$1.run(ForcedResourcePack.kt:18)
[WARNING] at java.lang.Thread.run(Thread.java:813)

**Comment by NichtStudioCode** [comment]
Seems to be an issue with the file uploader that is used, I am currently looking into alternatives. It should be working at the moment though.

**Comment by NichtStudioCode** [comment]
Since the issue was that the file uploader used does not have a 100% uptime, I have now implemented the ability to set up your own uploader on a web server, which should fix the problem.
