### ISSUE TITLE
Same with other guy, an error occurred while uploading the resource pack. Please help

### ISSUE THREAD

**Issue by EnDlEsSaL** [NichtStudioCode/MiniatureBlocks#2]
Just like the title said. Need the server log?

**Comment by NichtStudioCode** [comment]
Yes

**Comment by EnDlEsSaL** [comment]
[INFO] EnDlEsS_L issued server command: /cm cup

[WARNING] java.io.IOException: Server responded with non-OK status: 500

[WARNING] at de.studiocode.miniatureblocks.utils.HttpMultipartRequest.complete(HttpMultipartRequest.kt:63)

[WARNING] at de.studiocode.miniatureblocks.utils.FileIOUploadUtils.uploadFile(FileIOUploadUtils.kt:13)

[WARNING] at de.studiocode.miniatureblocks.resourcepack.ResourcePack.upload(ResourcePack.kt:49)

[WARNING] at de.studiocode.miniatureblocks.resourcepack.forced.ForcedResourcePack$force$1.run(ForcedResourcePack.kt:18)

[WARNING] at java.lang.Thread.run(Thread.java:813)

**Comment by NichtStudioCode** [comment]
Closed for duplicate
