### ISSUE TITLE
Unknown command - /miniature create

### ISSUE THREAD

**Issue by Verdux** [NichtStudioCode/MiniatureBlocks#4]
MiniatureBlocks - 0.5
Paper - 1.15.2

Any command with a space in it doesn't seem to be working. Just found the plugin today and decided to test it. So unsure if your latest additions broke it. No errors displayed in console, just what is said in the chat.

[https://i.gyazo.com/51dadf3ac2fc0043e187c531cd019d6e.gif](url)

**Comment by NichtStudioCode** [comment]
You have to give the miniature a name, so _/miniature create house_ for example.
